### ISSUE TITLE
Some items missing

### ISSUE THREAD

**Issue by DragonHunter003** [Lolkat76/infinity#3]
I've noticed some items missing in the source code, this probably happened when you added them to the repo. The items I've found that were missing were the silver and platinum coins along with their images. Could you add them to the development-consitency-changes branch and look if there are some other missing items? (Yes I actually made the typo while creating the branch)

**Comment by DragonHunter003** [comment]
I've also noted that the image of the poison-dart is missing, my guess is that all things after that are missing as well.

**Comment by Lolkat76** [comment]
Should be fixed now, I added things beneath the picture, including the picture.

**Comment by DragonHunter003** [comment]
Awesome, thanks for the help!
